os: linux
dist: xenial

services:
- xvfb

branches:
  only:
  - master
  - major
  - stable
  - latest
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^release\/\d+\.\d+\.x$/

addons:
  chrome: stable
  firefox: latest

language: node_js
node_js:
- '12'

cache:
- node_modules

before_install:
- export DISPLAY=:99.0
- npm install npm@7 -g
- npm --version
install:
- npm install
script:
- npm run test
env:
  global:
  - secure: VaeU6xjWymYoCIXNojAYams/WCcO3zYWESYwHOqXXd3U717+uww6kHq/mkk+BTX+ooG7ucfqjg3L2fAdITnw6ZhuY+IRit9JA4mBzrgcOSJ+T6NihfeW/kn23ppiMXn0MHnySm08cMrbPPMTE0y1NLYhgJmhb9lL0WzgmD6130uAJkSEb1nFjKEqg2lSqAg4G1L2Xql46UCZXNRLZePzHUxx5wlLRRiBUiKt6jg3U+ABY90/SvbT29jLeM+jBQM/iXHt4Vt7mETA+WQyePFZMsmDYpfcdEPH5KG3AdK893VNP9T0lOFOEJOEzWf9O1E3pfLAVF8m9CRFGMB8osVEnA3n5s8w6ZeiYH/vRmoKGeCQYg3C8aRNlDSXp/CfVRfWx9+cMRHN5eIqs3r+WXkU3W4UvXk7bn/RGt4dunnnm25x81v38TqEcgYuDMJDMCj/FY32pUfRPKKaZPU2cfxtbqOl8cmNyja7UzrS/ItI/xRpbm1qZWLH6kFw8C6k89rZuoAp8rqp/OzSx1L2+tOiw5pbbkoyG7IdqFzvgKO2h/u9H7tc4HGE2jSmLWpl/GS16nT+FtN1WTAQ038oVQHDeDkZfyNcJwJDOvAqT3VOIUvbEWRk/f3YryZqs6BYwrMzDRjoQi7VZNH5NE5T2BrNHyh+1hfTcdckbqx5B8Bjg8o=
  - secure: RWW/kYRdO93sZr3GurvlCjejxTLn4ljBA7CTwd55t8XESZ/+ggV6IJ2mt0mphSWqgNbMzHjFkKllOd1dovtHd3fpgfVo82kVPkP3TEg31vMaT1g4Guo//UcdD2nhxjwkLFFMJow3f52Gi3kr5iBPvOi0GznbLhlyU9+NE3nF+qy65PlnUsEActhPr7EOqOrngF/Ga0vejdy/U4SMqdh+kGTcnc7Ws0cOiIRvw2vSQ0RujmT6ooopH2JZSUSZHP0CMjOOX+O4BfgQWl3fv2g9WkfL4QUJ+OOJbvHMdSyzm2iPQqTJCoz8Hi/NYpdNpXMrGWJRcZBairjPtFnWCfzVlUQzyahJJm9MITN56Bf840gl3gvKJYqHAgK2bkxzPA9aO0shijCIj30RrnKp41JQcWhXgYl46nM7ph53T3y9hUnmE5fsDDlqLbtQlu9XGkj7GxyyHJH3/AOytPQTKeMv/sWohVE03oZXi4qlYtw6gidlh9Qv7jGStiICzkvVHJXYaBlKbrDmeLjBmfZRm0mH3hKgUfDeNogp5qhHVARypKFHXMJYRJG2bkrh52DdRgyAvYG7+BFpLX/12qU2alnTcT59BxBDtJFGbMBtXpc7e5fnt8bG8AxTRXZA2+ODf8WNCgY7Bf+7zpDxN/uZUn0eYbQHfq1eWdsSCmQEFZl/Gi4=
